<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>1</title>
</head>
<body>
    <form action="1.php" method="POST">
    <label for="">Velocidad</label> <input type="text" name="num1">
    <label for="">Tiempo</label> <input type="text" name="num2">
    <input type="submit" value="enviar">
    </form>
</body>
</html>